### ISSUE TITLE
release arm64 image has x86_64 binaries in it

### ISSUE THREAD

**Issue by brucejcooper** [davidcomerford/pyodbc-mssql-lambda-layer#1]
I think you may have uploaded the wrong version for the python 3.12 aarch64 version of your layer.  I downloaded it and it didn't work.  looking at the zip, it has python/pyodbc.cpython-312-x86_64-linux-gnu.so in it which indicates that it might be the wrong upload.

**Comment by brucejcooper** [comment]
rebuilding using docker worked just fine.

**Comment by davidcomerford** [comment]
I'm on it.

**Comment by davidcomerford** [comment]
Fixed a problem with the build workflow on the github side. 
Release 1.0.1 is the correct builds now. Thanks for taking the time to highlight this!
