### ISSUE TITLE
Runtime.ImportModuleError: No module named 'pyodbc'

### ISSUE THREAD

**Issue by erichaus** [davidcomerford/pyodbc-mssql-lambda-layer#2]
I've tried using this in my lambda function with runtime python3.12, but am receiving import error. I tested locally and it seems to import fine. How could I debug this or have you encountered this when deploying to the lambda?

**Comment by erichaus** [comment]
figured it out, had everything in /layer-root/python, needed to be at /layer-root (also copied a few things from working pyodbc python 3.8 layer)

**Comment by davidcomerford** [comment]
Glad you got it sorted
