### ISSUE TITLE
Any idea to support IBM iSeries database?

### ISSUE THREAD

**Issue by Jackznyu** [davidcomerford/pyodbc-mssql-lambda-layer#3]
Tried to make it work for IBM DB2 but it finally gave me this error:
[01000] [unixODBC][Driver Manager]Can't open lib '/opt/ibm/iaccess/lib/libcwbodbc.so' : file not found (0) (SQLDriverConnect)

For the dockerfile I added
`# Install IBM driver`
`RUN curl https://public.dhe.ibm.com/software/ibmi/products/odbc/rpms/ibmi-acs.repo | tee /etc/yum.repos.d/ibmi-acs.repo`
`RUN yum install -y ibm-iaccess`
`RUN export CFLAGS="-I/opt/ibm/iSeriesAccess/include $CFLAGS"`
`RUN export LDFLAGS="-L/opt/ibm/iSeriesAccess/lib64 $LDFLAGS"`

And in my code I also updated the LD_LIBRARY_PATH but still lambda can not find (or load?) that .so file. Do you have any thoughts?

**Comment by davidcomerford** [comment]
No idea, sorry.
