### ISSUE TITLE
  "errorType": "InterfaceError"

### ISSUE THREAD

**Issue by mkashifakram** [davidcomerford/pyodbc-mssql-lambda-layer#4]
getting this error

Test Event Name
(unsaved) test event

Response
{
  "errorMessage": "('28000', \"[28000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Login failed for user 'admin'. (18456) (SQLDriverConnect)\")",
  "errorType": "InterfaceError",
  "requestId": "",
  "stackTrace": [
    "  File \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n",
    "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
    "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
    "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
    "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
    "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
    "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
    "  File \"/var/task/lambda_function.py\", line 10, in <module>\n    lambda_handler(None,None)\n",
    "  File \"/var/task/lambda_function.py\", line 3, in lambda_handler\n    conn = pyodbc.connect(f'DRIVER={{ODBC Driver 18 for SQL Server}};SERVER=fgdfgfd.eu-west-2.rds.amazonaws.com;DATABASE=,y-db;UID=admin;PWD=admin;TrustServerCertificate=no')\n"
  ]
}

**Comment by davidcomerford** [comment]
This error tells us two things:
1. Connectivity to the database is working fine
2. The server is not permitting this "admin" user to login for whatever reason, incorrect password, locked account, etc.

**Comment by mkashifakram** [comment]
it works from the ec2 windows instance with same creds

**Comment by mkashifakram** [comment]
all sorted, typo in password

**Comment by davidcomerford** [comment]
I was thinking maybe it was a strange character not being parsed correctly.
Thanks for the update.
